# use ubuntu 20.04 for base image
FROM ubuntu:20.04

# set default working directory to /hello_world
WORKDIR /hello_world

# add metadata about images
LABEL author="Erlangga Yudi Pradana EE20"
LABEL version="0.1"
